import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">AccueilAdmin</Link>
        </li>
        <li>
          <Link to="/pgeconnexion">Pgeconnexion</Link>
        </li>
        <li>
          <Link to="/accueiluser">AccueilUser</Link>
        </li>
        <li>
          <Link to="/historiqueadmin">HistoriqueAdmin</Link>
        </li>
        <li>
          <Link to="/article">Article</Link>
        </li>
        <li>
          <Link to="/visualiserarticlesscaler">VisualiserarticlesScaler</Link>
        </li>
        <li>
          <Link to="/visualiserarticlesbaseedt">VisualiserarticlesbaseEDT</Link>
        </li>
        <li>
          <Link to="/accueiladminpopup">AccueilAdminpopup</Link>
        </li>
        <li>
          <Link to="/historiquetwo">HistoriqueTwo</Link>
        </li>
        <li>
          <Link to="/articletwo">ArticleTwo</Link>
        </li>
        <li>
          <Link to="/accueiladmintwo">AccueilAdminTwo</Link>
        </li>
        <li>
          <Link to="/visualiserarticlesscalertwo">
            VisualiserarticlesScalerTwo
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
